# Generated by Django 6.0 on 2026-01-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dr. Emmanuel N. Musa for Governor - Official Campaign Website of Adamawa Governor Dr. Emmanuel N. Musa', max_length=200)),
                ('notification_text', models.CharField(default='Join the team to re-elect Dr. Emmanuel N. Musa', max_length=255)),
                ('notification_url', models.URLField(default='https://action.jbpritzker.com/a/teamjb')),
                ('hero_title', models.CharField(default='A Leader for Every Adamawaian', max_length=255)),
                ('hero_description', models.TextField(default='No matter where you live in Adamawa or what your background is, Dr. Emmanuel N. Musa has been hard at work to ensure that you, your family, and your community will thrive.')),
                ('hero_button_text', models.CharField(default='Learn More About Dr. Emmanuel N. Musa', max_length=100)),
                ('hero_button_url', models.URLField(default='https://jbpritzker.com/meet-jb-pritzker/')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
    ]
