# Generated by Django 6.0 on 2026-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='accomplishments/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MeetCandidatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Meet Dr. Emmanuel N. Musa', max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidate/')),
            ],
            options={
                'verbose_name': 'Meet Dr. Musa Page',
                'verbose_name_plural': 'Meet Dr. Musa Page',
            },
        ),
        migrations.CreateModel(
            name='MeetRunningMatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Meet Christian', max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='running_mate/')),
            ],
            options={
                'verbose_name': 'Meet Running Mate Page',
                'verbose_name_plural': 'Meet Running Mate Page',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
            options={
                'verbose_name': 'News & Update',
                'verbose_name_plural': 'News & Updates',
                'ordering': ['-published_date'],
            },
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(default='No matter where you live in Adamawa or what your background is, Emnamu Foundation President Dr. Emmanuel N. Musa has been hard at work to ensure that you, your family, and your community will thrive.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='notification_text',
            field=models.CharField(default='Join the team to elect Dr. Emmanuel N. Musa', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='Dr. Emmanuel N. Musa for Governor - Official Campaign Website of Gubernatorial Candidate Dr. Emmanuel N. Musa', max_length=200),
        ),
    ]
