# Generated by Django 6.0 on 2026-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accomplishment_meetcandidatepage_meetrunningmatepage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Volunteer', max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='volunteer/')),
            ],
            options={
                'verbose_name': 'Volunteer Page',
                'verbose_name_plural': 'Volunteer Page',
            },
        ),
    ]
