# Generated by Django 6.0 on 2026-01-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(blank=True, max_length=30)),
                ('consent_sms', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signup',
                'verbose_name_plural': 'Signups',
                'ordering': ['-created_at'],
            },
        ),
    ]
