# Generated by Django 6.0 on 2026-01-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Main hero image at the top of the page', null=True, upload_to='home/hero/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meet_candidate_image',
            field=models.ImageField(blank=True, help_text="Image for the 'Meet Dr. Musa' section", null=True, upload_to='home/candidate/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for the launch video', null=True, upload_to='home/video/'),
        ),
    ]
