# Generated by Django 6.0 on 2026-01-05 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homepage_hero_image_homepage_meet_candidate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetcandidatepage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
