# Generated by Django 6.0 on 2026-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_meetcandidatepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='action_button_text',
            field=models.CharField(default='Learn More', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='action_button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='action_title',
            field=models.CharField(default='Take Action', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='connect_title',
            field=models.CharField(default='Get Connected', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='join_disclaimer',
            field=models.TextField(default='By submitting your mobile phone number you are agreeing to receive periodic text messages from this organization. Message and data rates may apply. Text HELP for more information. Text STOP to stop receiving messages.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='join_title',
            field=models.CharField(default='Join #TeamJB', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meet_candidate_button_text',
            field=models.CharField(default='Learn More About Dr. Emmanuel N. Musa', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meet_candidate_description',
            field=models.TextField(default='No matter where you live in Adamawa or what your background is, Dr. Emmanuel N. Musa has been hard at work to ensure that you, your family, and your community will thrive.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meet_candidate_eyebrow',
            field=models.CharField(default='Meet Dr. Emmanuel N. Musa', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meet_candidate_title',
            field=models.CharField(default='A Leader for Every Adamawaian', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='threads_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=0HCOrIr7Umo', help_text='YouTube URL for the video'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
