# Generated by Django 6.0 on 2026-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homepage_action_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(default='Emnamu Foundation President Dr. Emmanuel N. Musa', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_slogan',
            field=models.CharField(default='Keep Adamawa moving forward', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='running_mate_button_text',
            field=models.CharField(default='Learn more about Christian', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='running_mate_description',
            field=models.TextField(default='From serving as a State Representative to Deputy Governor to the Adamawa Air National Guard, Christian Mitchell has dedicated himself to improving the lives and livelihoods of all Adamawaians. He is running for Lieutenant Governor to keep our state moving forward.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='running_mate_image_1',
            field=models.ImageField(blank=True, help_text='First image for running mate section', null=True, upload_to='home/running_mate/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='running_mate_image_2',
            field=models.ImageField(blank=True, help_text='Second image for running mate section', null=True, upload_to='home/running_mate/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='running_mate_title',
            field=models.CharField(default='Meet Christian', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision_button_text',
            field=models.CharField(default="Learn More About Dr. Musa's Vision", max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision_description',
            field=models.TextField(default='Through the Emnamu Foundation, Dr. Emmanuel N. Musa has demonstrated the leadership to make our state one of the best in the nation in education, youth mental health, workforce development, and fighting climate change. He will create jobs, balance our budget, and protect our freedoms. Discover how Dr. Emmanuel N. Musa will lead the way on issues you care about.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision_image',
            field=models.ImageField(blank=True, help_text='Image for the vision/accomplishments section', null=True, upload_to='home/vision/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision_title',
            field=models.CharField(default='Adamawa Is Heading In The Right Direction', max_length=255),
        ),
    ]
