# Generated by Django 6.0 on 2026-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homepage_hero_eyebrow_homepage_hero_slogan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='join_button_text',
            field=models.CharField(default='Sign Up', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_button_text',
            field=models.CharField(default='Play Launch Video', max_length=100),
        ),
    ]
