# Generated by Django 6.0 on 2026-01-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_homepage_join_button_text_homepage_video_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload website logo', null=True, upload_to='site_settings/'),
        ),
    ]
