# Generated by Django 6.0 on 2026-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_emailcampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='join_title',
            field=models.CharField(default='Join #TeamDr.Emmanuel', max_length=255),
        ),
    ]
