# Generated by Django 6.0 on 2026-01-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_homepage_join_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Upload footer logo', null=True, upload_to='site_settings/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_logo',
            field=models.ImageField(blank=True, help_text='Upload header logo', null=True, upload_to='site_settings/'),
        ),
    ]
