# Generated by Django 6.0 on 2026-01-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_homepage_footer_logo_homepage_header_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='meet_candidate_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='home/candidate/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meet_candidate_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='home/candidate/'),
        ),
    ]
