# Generated by Django 6.0 on 2026-01-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_homepage_meet_candidate_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='notification_url',
            field=models.CharField(default='/signup/', max_length=255),
        ),
    ]
