# Generated by Django 6.0 on 2026-01-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_homepage_notification_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetRunningMatePage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='running_mate_button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='running_mate_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='running_mate_image_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='running_mate_image_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='running_mate_title',
        ),
    ]
